/*Avis Oh Xin Wan UOW ID:8465678
  Assignment 2 Task 1 Create Tables*/
CREATE TABLE DIPLOMA(
	code    VARCHAR(5) 	NOT NULL,
    name 	VARCHAR(50) NOT NULL,
 CONSTRAINT DIPLOMA_PK PRIMARY KEY(code),
 CONSTRAINT DIPLOMA_CK UNIQUE(name));
 
 CREATE TABLE MODULE(
	code    VARCHAR(4) 	NOT NULL,
    name 	VARCHAR(30) NOT NULL,
    hours	DECIMAL(2)	NOT NULL,
    fee		DECIMAL(4)	NULL,
 CONSTRAINT MODULE_PK PRIMARY KEY(code),
 CONSTRAINT HOURS_CH1 CHECK (hours > 30) );
 
CREATE TABLE DIPMOD(
	dip_code    VARCHAR(5) 	NOT NULL,
    mod_code 	VARCHAR(4)  NOT NULL,
 CONSTRAINT DIPMOD_FK1 FOREIGN KEY(dip_code) REFERENCES DIPLOMA(code),
 CONSTRAINT DIPMOD_FK2 FOREIGN KEY(mod_code) REFERENCES MODULE(code) );
 
 CREATE TABLE LECTURER(
	emp_id    VARCHAR(4) 	NOT NULL,
    name 	  VARCHAR(25)   NOT NULL,
    dob		  DATE		    NULL,
    gender	  VARCHAR(1)	NOT NULL,
    email	  VARCHAR(35)	NOT NULL,
 CONSTRAINT LECTURER_PK PRIMARY KEY(emp_id),
 CONSTRAINT LECTURER_CK UNIQUE(email),
 CONSTRAINT GENDER_CH1 CHECK (gender = 'M' OR gender = 'F') );
 
 CREATE TABLE SPECIALTY(
	emp_id   VARCHAR(4) 	NOT NULL,
    topic	 VARCHAR(35) 	NOT NULL,
 CONSTRAINT SPECIALTY_FK1 FOREIGN KEY(emp_id) REFERENCES LECTURER(emp_id));
 